table_list = [
    "MSysAccessStorage",
    "MSysAccessXML",
    "MSysACEs",
    "MSysComplexColumns",
    "MSysNameMap",
    "MSysNavPaneGroupCategories",
    "MSysNavPaneGroups",
    "MSysNavPaneGroupToObjects",
    "MSysNavPaneObjectIDs",
    "MSysObjects",
    "MSysQueries",
    "MSysRelationships",
    "MSysResources",
    "Architecture",
    "Assumption",
    "Category",
    "COI",
    "Component",
    "ComponentKeyData",
    "Deficiency",
    "DefinedTerm",
    "Document",
    "ExternalConstraint",
    "ExternalText",
    "Function",
    "Image",
    "Item",
    "Link",
    "LinkArchitectureArchitecture",
    "LinkArchitectureComponent",
    "LinkArchitectureOperationalActivity",
    "LinkAssumptionAssumption",
    "LinkCategoryCategory",
    "LinkCOICOI",
    "LinkCOIMOE",
    "LinkCOIOperationalActivity",
    "LinkComponentComponent",
    "LinkComponentDeficiency",
    "LinkComponentInherits",
    "LinkComponentKeyDataComponent",
    "LinkComponentKeyDataComponentKeyData",
    "LinkComponentLink",
    "LinkComponentMission",
    "LinkDeficiencyDeficiency",
    "LinkDeficiencyFunction",
    "LinkDefinedTermDefinedTerm",
    "LinkDocumentComponent",
    "LinkDocumentDeficiency",
    "LinkDocumentDefinedTerm",
    "LinkDocumentDocument",
    "LinkDocumentExternalConstraint",
    "LinkDocumentExternalText",
    "LinkDocumentFunction",
    "LinkDocumentItem",
    "LinkDocumentLink",
    "LinkDocumentOperationalActivity",
    "LinkDocumentOperationalItem",
    "LinkDocumentOperationalNeed",
    "LinkDocumentOrganisation",
    "LinkDocumentPerformer",
    "LinkDocumentProduct",
    "LinkDocumentProject",
    "LinkDocumentReferenceDocument",
    "LinkDocumentRisk",
    "LinkDocumentStateMode",
    "LinkDocumentVerificationProcedure",
    "LinkExternalConstraintExternalConstraint",
    "LinkExternalConstraintLink",
    "LinkExternalTextExternalText",
    "LinkFunctionComponent",
    "LinkFunctionFunction",
    "LinkFunctionInput",
    "LinkFunctionOperationalNeed",
    "LinkFunctionOutput",
    "LinkItemItem",
    "LinkLinkItem",
    "LinkLinkLink",
    "LinkLinkSystemRequirement",
    "LinkMissionDocument",
    "LinkMissionMission",
    "LinkMOEMOE",
    "LinkMOEMOP",
    "LinkMOPMOP",
    "LinkMOPSystemRequirement",
    "LinkOperationalActivityExternalConstraint",
    "LinkOperationalActivityInput",
    "LinkOperationalActivityOperationalActivity",
    "LinkOperationalActivityOutput",
    "LinkOperationalActivityReferenceDocument",
    "LinkOperationalConnectionLink",
    "LinkOperationalConnectionOperationalConnection",
    "LinkOperationalConnectionOperationalItem",
    "LinkOperationalItemItem",
    "LinkOperationalItemOperationalItem",
    "LinkOperationalNeedOperationalActivity",
    "LinkOperationalNeedOperationalNeed",
    "LinkOperationalNeedSystemRequirement",
    "LinkOrganisationComponent",
    "LinkOrganisationOrganisation",
    "LinkOrganisationPerformer",
    "LinkPerformerOperationalActivity",
    "LinkPerformerOperationalConnection",
    "LinkPerformerPerformer",
    "LinkProductComponent",
    "LinkProductProduct",
    "LinkProjectComponent",
    "LinkProjectProduct",
    "LinkProjectProject",
    "LinkReferenceDocumentReferenceDocument",
    "LinkRiskComponent",
    "LinkRiskExternalConstraint",
    "LinkRiskOperationalNeed",
    "LinkRiskRisk",
    "LinkRiskSystemRequirement",
    "LinkScriptScript",
    "LinkStateModeComponent",
    "LinkStateModeFunction",
    "LinkStateModeStateMode",
    "LinkSystemRequirementCategory",
    "LinkSystemRequirementComponent",
    "LinkSystemRequirementDocument",
    "LinkSystemRequirementExternalConstraint",
    "LinkSystemRequirementFunction",
    "LinkSystemRequirementRefines",
    "LinkSystemRequirementSystemRequirement",
    "LinkSystemRequirementVerificationCondition",
    "LinkSystemRequirementVerificationProcedure",
    "LinkVerificationConditionVerificationCondition",
    "LinkVerificationProcedureComponent",
    "LinkVerificationProcedureVerificationProcedure",
    "Mission",
    "MOE",
    "MOP",
    "OperationalActivity",
    "OperationalConnection",
    "OperationalItem",
    "OperationalNeed",
    "OperationalNode",
    "Organisation",
    "Performer",
    "Product",
    "Project",
    "ReferenceDocument",
    "Risk",
    "Script",
    "StateMode",
    "sysCombo",
    "sysLogin",
    "sysPreferences",
    "sysSchema",
    "sysTableVersions",
    "SystemRequirement",
    "sysUID",
    "USysRibbons",
    "VerificationCondition",
    "VerificationProcedure",
]

basic_columns = [
    "ID",
    "Name",
    "Number",
    "Description",
    "Number1",
    "Number2",
    "Number3",
    "Number4",
    "Number5",
    "Number6",
]

parts = []
(240, 'Context')
(533, 'Brakes Subsystem')
(535, 'Chassis Subsystem')
(537, 'Suspension Subsystem')
(804, 'Exterior Subsystem')
(805, 'Interior Subsystem')
(806, 'Array Subsystem')
(538, 'Drive Train Subsystem')
(539, 'Steering Subsystem')
(769, 'Mission Control Subsystem')
(770, 'Race Strategy Subsystem')
(771, 'Embedded Subsystem')
(792, 'Race Car')
(793, 'Telemetry Subsystem')
(794, 'User Interface Subsystem')
(795, 'Safe State Subsystem')
(796, 'Battery Subsystem')
